// <auto-generated />
using Koop.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Koop.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260520135611_AddAccountingRecords")]
    partial class AddAccountingRecords
    {
    }
}
